### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arturobandissimo** [LOISGALLAUD/MacroScraper#9]
Hi, wondering if you might be able to assist as to why this is not working for me on Mac Silicon:
Also, is there a way to have the program run in English?

IL EST IMPORTANT D'ECRIRE EXACTEMENT LE NOM DE L'ARTISTE
Entrez le nom de l'artiste: artist
Traceback (most recent call last):
  File "/app/./src/Main.py", line 29, in <module>
    macroScraper = MacroScraper(logs)
                   ^^^^^^^^^^^^^^^^^^
  File "/app/src/MacroScraper.py", line 35, in __init__
    self.WD = WorkingDirectory()
              ^^^^^^^^^^^^^^^^^^
  File "/app/src/WD.py", line 35, in __init__
    self.path = os.path.join(os.environ['USERPROFILE'], "Music\\MacroScraper\\")
                             ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'USERPROFILE'

**Comment by LOISGALLAUD** [comment]
What is your OS? On windiws it is working fine.

If you want a quick debug, just replace os.path.join(.... by the path to your music directory followed by "MacroScraper".

I'm currently working on using an api to download the music, because it is kind of slow. I planned to write the update in english.

**Comment by arturobandissimo** [comment]
MacOS Monterey...

Thanks maybe there is something incompatible in my setup.
